sudo: false
language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.yarn
    - ~/.cache
notifications:
  email: false
node_js: '12'
install: yarn install
script: yarn run validate
branches:
  only: master
