sudo: false
language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.cache/yarn
    - ~/.cache/Cypress
notifications:
  email: false
node_js: '12'
install:
  - yarn install --frozen-lockfile
  - yarn cypress install
  - yarn cypress verify
script: yarn run validate
branches:
  only: master
